feat: implement parallel diffing
filecoin-project/go-hamt-ipld pull request #100
Opened 2022-04-28 02:36 UTC by frrist

2022-05-03 14:23 UTC, Stebalien commented on diff_parallel.go
> +	out := make(chan *Change)
Usually, 1-2x the max number of workers.

2022-05-03 14:23 UTC, Stebalien commented on diff_parallel.go
> +		done <- struct{}{}
nit: closing done channels can be a bit easier to reason about. Also makes it possible to `defer close(done)`.

2022-05-03 14:23 UTC, Stebalien commented on diff_parallel.go
> +func ParallelDiff(ctx context.Context, prevBs, curBs cbor.IpldStore, prev, cur cid.Cid, maxWorkers int64, opts ...Option) ([]*Change, error) {
Any reason not to return a channel of changes?

2022-05-03 14:23 UTC, Stebalien commented on diff_parallel.go
> +	grp.Go(func() error {
We definitely don't need an extra goroutine here.

2022-05-03 14:23 UTC, Stebalien commented on diff_parallel.go
> +func doParallelDiffNode(ctx context.Context, pre, cur *Node, depth int, maxWorkers int64) ([]*Change, error) {
If possible, it would be really nice to dedup this code with the non-parallel version. It seems like we could have a core "diff node" function that takes `add`, `remove`, and `change` callbacks.

2022-05-04 15:45 UTC, frrist commented on diff_parallel.go
> +	out := make(chan *Change)
done.

2022-05-04 16:20 UTC, Stebalien requested changes
Also, in general, you need to either:

1. Select on the context everywhere.
2. Ensure that you drain channels _everywhere_.

It's usually easier to select on the context and just let everything shut down async. But it's cleaner to carefully drain channels. Up to you.

2022-05-04 16:20 UTC, Stebalien commented on diff_parallel.go
> +		close(done)
nit: defer this.

2022-05-04 16:20 UTC, Stebalien commented on diff_parallel.go
> +	return changes, nil
```suggestion
	err := differ.grp.Wait()
	close(out)
	<-done

	return changes, err
```

It's the "nicer" thing to do.

2022-05-04 16:20 UTC, Stebalien commented on diff_parallel.go
> +			s.grp.Go(func() error {
Start a fixed number of workers and have them read directly from `s.out`. You can then drop the semaphore, and avoid spawning one goroutine per task.

2022-05-04 16:20 UTC, Stebalien commented on diff_parallel.go
> +func ParallelDiff(ctx context.Context, prevBs, curBs cbor.IpldStore, prev, cur cid.Cid, workers int64, opts ...Option) ([]*Change, error) {
I would consider returning a channel of changes.

2022-05-04 16:20 UTC, Stebalien commented on diff_parallel.go
> +		}()
I _think_ you can just close `s.in`, right?

2022-05-04 16:20 UTC, Stebalien commented on diff_parallel.go
> +		}()
```suggestion
		defer close(s.out)
```

2022-05-04 16:20 UTC, Stebalien commented on diff_parallel.go
> +				}
You probably need to select on the context here.

2022-05-04 17:24 UTC, Stebalien commented on diff_parallel.go
> +			s.grp.Go(func() error {
You can spin up each worker in a single error group. If a worker runs into an error, it returns it.

2022-05-04 17:36 UTC, frrist commented on diff_parallel.go
> +func ParallelDiff(ctx context.Context, prevBs, curBs cbor.IpldStore, prev, cur cid.Cid, workers int64, opts ...Option) ([]*Change, error) {
The use case I am targeting with this doesn't require that interface, care if this comes in a follow on when we need it?

2022-05-04 18:39 UTC, frrist commented on diff_parallel.go
> +			}
I don't think this is needed given that I am selecting on the ctx in the select statements and returning w/e the value of ctx.Error is there, ya?

2022-05-04 18:58 UTC, Stebalien commented on diff_parallel.go
> +			}
Probably not? But there's no guarantee which one is selected first, so it can help to check for a context error early. Otherwise, you can keep going for a while.

2022-05-04 19:09 UTC, Stebalien commented on diff_parallel.go
> +		stack:      []*task{},
You can just set this to `rootTasks` (or leave it uninitialized).

2022-05-04 19:09 UTC, Stebalien commented on diff_parallel.go
> +	out chan *task
```suggestion
	// inbound and outbound tasks
	in, out chan *task
```

2022-05-04 19:09 UTC, Stebalien commented on diff_parallel.go
> +	defer s.workerWg.Done()
nit: rename to `taskWg`, `outstandingTasks`, etc.

2022-05-04 19:14 UTC, Stebalien commented on diff_parallel.go
> +		defer close(s.out)
> Also, in general, you need to either:
> 1.  Select on the context everywhere.
> 2.  Ensure that you drain channels everywhere.
> 
> It's usually easier to select on the context and just let everything shut down async. But it's cleaner to carefully drain channels. Up to you.

I was wrong here. Because we're counting tasks, you _do_ need to drain the channels so you can correctly update the waitgroup. Basically:

```go
defer func() {
    close(s.out)
    // Because the workers may have exited early (due to the context being canceled).
    for range s.out {
        wg.Done()
    }
    // Because the workers may have enqueued additional tasks.
    for range s.in {
        wg.Done()
    }
   // now, the waitgroup should be at 0, and the goroutine that was _waiting_ on it should have exited.
}()
```

2022-05-05 14:24 UTC, Stebalien approved these changes

2022-05-05 19:11 UTC, merged